import type { Metadata } from 'next';
import './globals.css';
import { SideBar } from '@/features/root/components/side-bar';
import { css } from '@/styled-system/css';
import { Grid } from '@/styled-system/jsx';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'SMG経営塾',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const pathname = headersList.get('x-pathname') || '';
  const publicPaths = ['/login', '/forgotPassword', '/reset-password'];
  const showSidebar = !publicPaths.some((path) => pathname.startsWith(path));

  return (
    <html lang="ja">
      <body>
        <Grid
          gap={0}
          gridTemplateColumns={showSidebar ? 'auto 1fr' : '1fr'}
          h={'100%'}
        >
          {showSidebar && <SideBar />}
          <div className={css({ bg: '#cbcacfff', overflow: 'auto' })}>
            {children}
          </div>
        </Grid>
      </body>
    </html>
  );
}
