import { css } from '@/styled-system/css';

export const styles = {
	searchContainer: css({
		display: 'flex',
		flexDirection: 'row',
		gap: '2',
		alignItems: 'center',
		padding: '4',
		bg: 'white',
		rounded: 'lg',
		shadow: 'md',
		marginBottom: '4',
		flexWrap: 'nowrap',
		'@media (max-width: 768px)': {
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '2',
			padding: '2',
		},
	}),
	searchInputContainer: css({
		position: 'relative',
		display: 'flex',
		alignItems: 'center',
		gap: '2',
		width: '100%',
		'@media (max-width: 768px)': {
			width: '100%',
			minWidth: 'auto',
		},
	}),
	searchInputWrapper: css({
		position: 'relative',
		width: 'full',
	}),
	searchIcon: css({
		position: 'absolute',
		left: '3',
		top: '1/2',
		transform: 'translateY(-50%)',
		color: 'gray.400',
	}),
	sortContainer: css({
		display: 'flex',
		alignItems: 'center',
		gap: '2',
		width: '200px',
		'@media (max-width: 768px)': {
			width: '100%',
			minWidth: 'auto',
			marginRight: '0',
			marginBottom: '2',
		},
	}),
	filterButton: css({
		display: 'flex',
		alignItems: 'center',
		gap: '2',
		px: '3',
		py: '2',
		border: '1px solid',
		borderColor: 'gray.200',
		rounded: 'md',
		bg: 'white',
		color: 'gray.700',
		_hover: {
			bg: 'gray.50',
			borderColor: 'gray.300',
		},
		transition: 'all 0.2s ease-in-out',
		cursor: 'pointer',
		_active: {
			bg: 'gray.100',
			transform: 'scale(0.98)',
		},
		width: '120px',
		justifyContent: 'space-between',
		'@media (max-width: 768px)': {
			width: '100%',
			minWidth: 'auto',
			marginLeft: '0',
		},
	}),
	popoverContent: css({
		width: '130px',
		p: '6',
		bg: 'white',
		rounded: 'lg',
		shadow: 'xl',
		border: '1px solid',
		borderColor: 'gray.100',
		'@media (max-width: 768px)': {
			width: '100%',
			p: '4',
		},
	}),
	filterSection: css({
		spaceY: '6',
		'@media (max-width: 768px)': {
			spaceY: '4',
		},
	}),
	filterTitle: css({
		fontWeight: 'semibold',
		mb: '4',
		fontSize: 'lg',
		color: 'gray.800',
		borderBottom: '1px solid',
		borderColor: 'gray.200',
		pb: '2',
	}),
	filterItem: css({
		display: 'flex',
		alignItems: 'center',
		spaceX: '3',
		rounded: 'md',
		_hover: {
			bg: 'gray.50',
		},
		transition: 'all 0.2s ease-in-out',
	}),
	locationSection: css({
		spaceY: '3',
		py: '2',
		bg: 'gray.50',
		rounded: 'md',
		p: '3',
	}),
	locationTitle: css({
		textStyle: 'sm',
		fontWeight: 'medium',
		color: 'gray.700',
		mb: '2',
		display: 'flex',
		alignItems: 'center',
		gap: '2',
	}),
	searchButton: css({
		bg: 'gray.800',
		color: 'white',
		px: '6',
		py: '2',
		rounded: 'md',
		_hover: {
			bg: 'gray.900',
		},
		transition: 'all 0.2s',
		ml: 'auto',
		display: 'flex',
		alignItems: 'center',
		gap: '2',
		fontWeight: 'medium',
		'@media (max-width: 768px)': {
			width: '100%',
			ml: '0',
			justifyContent: 'center',
		},
		'@media (max-width: 398px)': {
			'& svg': {
				display: 'inline-block',
			},
		},
	}),
	filterTagsContainer: css({
		display: 'flex',
		flexWrap: 'wrap',
		gap: '2',
		mt: '3',
	}),
	filterTag: css({
		bg: 'blue.100',
		color: 'blue.800',
		textStyle: 'xs',
		px: '2',
		py: '1',
		rounded: 'full',
	}),
	label: css({
		textStyle: 'sm',
		whiteSpace: 'nowrap',
		fontWeight: 'medium',
		color: 'gray.700',
	}),
	input: css({
		width: 'full',
		border: '1px solid',
		borderColor: 'gray.200',
		outline: 'none',
		rounded: 'sm',
		pl: '4',
		pr: '4',
		color: 'black',
		fontSize: 'sm',
		bg: 'gray.100',
		_placeholder: {
			color: 'gray.400',
		},
		_focus: {
			outline: 'none',
			ring: '0',
			borderColor: 'gray.200',
		},
	}),
	bottomRow: css({
		display: 'flex',
		gap: '2',
		alignItems: 'center',
		width: '100%',
		'@media (max-width: 768px)': {
			flexDirection: 'column',
			gap: '2',
			alignItems: 'stretch',
		},
	}),
};
